### ISSUE TITLE
Bonito plotting example does not include any plots

### ISSUE THREAD

**Issue by yakir12** [OxygenFramework/Oxygen.jl#173]
This might be intended, but since the other two examples (CairoMakie and WGLMakie) do produce plots, I assumed that the Bonito one would do too.

**Comment by ndortega** [comment]
That's a good point. I left out the graph embedding to showcase rendering a `Bonito.App` object and keep the examples brief - but this is probably more confusing since most people would expect to see a graph. 

I'll go back and embed a similar heatmap example into bonito app to make this use case clearer
