### ISSUE TITLE
Server Sent Events Support

### ISSUE THREAD

**Issue by BrandonEscamilla** [OxygenFramework/Oxygen.jl#81]
Hi, I was wondering if there are any plans to support Server Sent Events in Oxygen.jl? Thank you in advance! 😄

**Comment by ndortega** [comment]
Hi @BrandonEscamilla ,

While we don't have a special syntax for SSE, HTTP.jl the library Oxygen is built on does support this. For features like this, all I could do is provide a cleaner syntax for attaching logic to HTTP event streams. 

https://juliaweb.github.io/HTTP.jl/stable/examples/#Server-Sent-Events

**Comment by BrandonEscamilla** [comment]
Yes it makes sense, in fact, i would like to know how to use some features from HTTP.jl in Oxygen like connection_limit.

**Comment by ndortega** [comment]
Hi @BrandonEscamilla , 

Sorry about the long turnaround: 

Because Oxygen.jl is built on top of HTTP.jl it has access to all the same configuration properties. To pass in parameters to the underlying HTTP.Server, just pass your keyword arguments to the `serve()` function in Oxygen. 

Here's the documentation around what options you can pass. https://juliaweb.github.io/HTTP.jl/stable/server/#HTTP.serve

Now about connection limits, as far as I understand that's only for clients when they want to make external http requests. Oxygen doesn't try to extend or change this functionality, all it does is provide a simple abstraction for building web applications. 
https://github.com/JuliaWeb/HTTP.jl/blob/master/docs/src/client.md#connection_limit

**Comment by frankier** [comment]
Probably relevant: https://github.com/ndortega/Oxygen.jl/pull/117

**Comment by rodrigojim** [comment]
Hello @ndortega , I see that support for server sent events has been added to the library. Is middleware supported natively with the SSE? 
Thank you.

**Comment by ndortega** [comment]
Hi @rodrigojim, 

It isn't officially live yet, but it will be soon! To answer your question, both new handlers are compatible with middleware, path parameters, and the router higher-order function that comes with oxygen. Any connection requests will go through your middleware as normal requests before getting "upgraded" and passed to your stream or websocket handlers.

**Comment by BrandonEscamilla** [comment]
Thanks for supporting this feature @ndortega!
